algoritmo "aritmeticatreino"
var
ab: inteiro
ex: real
inthi:inteiro
rzq:real
shen: real
coshen:real
than: real
gr: real
phi: real

inicio
ab <- abs(-10)
ex <- exp(3,2)
inthi <-int(3.9)
rzq <-raizq(25)
phi <- pi()
shen <-sen(0.523)
coshen <-cos(0.523)
than <- tan(0.523)
gr <- graupRad(30)

escreval(ex)
escreval(ab)
escreval(inthi)
escreval(rzq)
escreval(phi)
escreval(shen)
escreval(coshen)
escreval(than)
fimalgoritmo