algoritmo "operadoresrelacionaveis"
var
a, b, c: inteiro
inicio
a <- 10
b <- 7
c <- 9



escreval("a é maior que c?",(a>c))  //a é maior que c?
escreval("c é menor que b?",(c<b))//c é menos que b?
escreval("a é maior ou igual a c?",(a>=c) //a é maior ou igual a c
escreval(" b é menor ou igual a a?", (b<=c))//b é menor ou igual a c
escreval("c é igual a b?", (c=c))        //c é igual a c?
escreval("b é diferente de c?", (b<>c))  //b é diferente de c?



fimalgoritmo